spring.application.name=clinic-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_booking_db
spring.datasource.username=postgres
spring.datasource.password=@Bon12345

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# VNPay
vnpay.tmnCode=DRRSU9G9
vnpay.hashSecret=NLDFLA19074KJA0DA7CTXFCXNR6PF23K
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/payment/vnpay-return

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trietminhpham79@gmail.com
spring.mail.password=vqet bvod qlik bmlf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.port=8080
